// <auto-generated />
using System;
using KTransport.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KTransport.API.Migrations
{
    [DbContext(typeof(KTransportDbContext))]
    [Migration("20260920150539_MultiTenancyAndGenericShipmentSchema")]
    partial class MultiTenancyAndGenericShipmentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KTransport.API.Models.BillType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("BillType_pkey");

                    b.ToTable("BillType", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Challan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("ChallanDate")
                        .HasColumnType("date")
                        .HasColumnName("ChallanDate");

                    b.Property<string>("ChallanNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ChallanNo");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DriverName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DriverName");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FromLocation");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LorryNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LorryNo");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("Remarks");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("TenantId");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ToLocation");

                    b.Property<string>("VoiceDriverName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("VoiceDriverName");

                    b.HasKey("Id")
                        .HasName("challan_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("TenantId");

                    b.ToTable("challan", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.ChallanDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BillNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("BillNo");

                    b.Property<int?>("BillTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("BillTypeId");

                    b.Property<long>("ChallanId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChallanId");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ConsigneeName");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Destination")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Destination");

                    b.Property<decimal?>("FreightAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("FreightAmount");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Remarks");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("TenantId");

                    b.HasKey("Id")
                        .HasName("challanDetail_pkey");

                    b.HasIndex("BillTypeId");

                    b.HasIndex("ChallanId");

                    b.ToTable("challandetail", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("DdCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("dd_charge")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("Freight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("freight")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("GrandTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("grand_total");

                    b.Property<decimal?>("Hamali")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("hamali")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("OtherCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("other_charge")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("ServiceCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("service_charge")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("StCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("st_charge")
                        .HasDefaultValueSql("0");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("charges_pkey");

                    b.HasIndex(new[] { "BillId" }, "charges_bill_id_key")
                        .IsUnique();

                    b.ToTable("charges", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.ChargeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<decimal>("DefaultAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("default_amount");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTaxable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_taxable");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("charge_types_pkey");

                    b.HasIndex("TenantId");

                    b.ToTable("charge_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FREIGHT",
                            DefaultAmount = 0m,
                            IsActive = true,
                            IsTaxable = true,
                            Name = "Base Freight",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 2,
                            Code = "HAMALI",
                            DefaultAmount = 0m,
                            IsActive = true,
                            IsTaxable = false,
                            Name = "Loading / Hamali",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 3,
                            Code = "DOOR_DELIVERY",
                            DefaultAmount = 0m,
                            IsActive = true,
                            IsTaxable = true,
                            Name = "Door Delivery (DD)",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 4,
                            Code = "STATION_CHARGE",
                            DefaultAmount = 0m,
                            IsActive = true,
                            IsTaxable = false,
                            Name = "Stationary / ST Charge",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = 5,
                            Code = "TOLL_SURCHARGE",
                            DefaultAmount = 0m,
                            IsActive = true,
                            IsTaxable = false,
                            Name = "Toll & Surcharge",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("KTransport.API.Models.GoodsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("article");

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rate");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("goods_details_pkey");

                    b.HasIndex("BillId");

                    b.ToTable("goods_details", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.GstBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingClerk")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("booking_clerk");

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("text")
                        .HasColumnName("consignee_address");

                    b.Property<string>("ConsigneeGstNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("consignee_gst_no");

                    b.Property<string>("ConsigneeMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consignee_mobile");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consignee_name");

                    b.Property<string>("Consigneeraddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consigneeraddress");

                    b.Property<string>("ConsignerGstNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("consigner_gst_no");

                    b.Property<string>("ConsignerMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consigner_mobile");

                    b.Property<string>("ConsignerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consigner_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("DeliveryStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_location");

                    b.Property<decimal?>("GoodsValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("goods_value");

                    b.Property<DateOnly?>("GrDate")
                        .HasColumnType("date")
                        .HasColumnName("gr_date");

                    b.Property<string>("GrNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gr_no");

                    b.Property<string>("GstPaidBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gst_paid_by");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Paid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("paid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<decimal?>("Tbb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tbb");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_location");

                    b.Property<decimal?>("ToPay")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("to_pay");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TruckNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("truck_no");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("gst_bills_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "GrNo" }, "gst_bills_gr_no_key")
                        .IsUnique();

                    b.ToTable("gst_bills", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.NumberingSequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("CurrentValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("current_value");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("FormatPattern")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("{PREFIX}-{YEAR}-{SEQ}")
                        .HasColumnName("format_pattern");

                    b.Property<int>("Padding")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("padding");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prefix");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("numbering_sequences_pkey");

                    b.HasIndex(new[] { "TenantId", "EntityType", "Year" }, "numbering_sequences_tenant_entity_year_key")
                        .IsUnique();

                    b.ToTable("numbering_sequences", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Shipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BookingClerk")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("booking_clerk");

                    b.Property<string>("ConsigneeAddress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("consignee_address");

                    b.Property<string>("ConsigneeGstNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("consignee_gst_no");

                    b.Property<string>("ConsigneeMobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("consignee_mobile");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("consignee_name");

                    b.Property<string>("ConsignorAddress")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("consignor_address");

                    b.Property<string>("ConsignorGstNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("consignor_gst_no");

                    b.Property<string>("ConsignorMobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("consignor_mobile");

                    b.Property<string>("ConsignorName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("consignor_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("DueAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("due_amount");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("from_location");

                    b.Property<decimal>("GoodsValue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("goods_value");

                    b.Property<decimal>("GrandTotal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("grand_total");

                    b.Property<string>("GstPaidBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gst_paid_by");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("PaidAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("paid_amount");

                    b.Property<int>("PaymentTerm")
                        .HasColumnType("integer")
                        .HasColumnName("payment_term");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<DateOnly>("ShipmentDate")
                        .HasColumnType("date")
                        .HasColumnName("shipment_date");

                    b.Property<string>("ShipmentNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shipment_no");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TaxTreatment")
                        .HasColumnType("integer")
                        .HasColumnName("tax_treatment");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("to_location");

                    b.Property<decimal>("TotalFreight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_freight");

                    b.Property<decimal>("TotalOtherCharges")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_other_charges");

                    b.Property<decimal>("TotalTaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_tax_amount");

                    b.Property<string>("TruckNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("truck_no");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("shipments_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "TenantId", "ShipmentNo" }, "shipments_tenant_shipment_no_key")
                        .IsUnique();

                    b.ToTable("shipments", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.ShipmentChargeItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("amount");

                    b.Property<string>("ChargeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("charge_name");

                    b.Property<int?>("ChargeTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("charge_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsTaxable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_taxable");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("shipment_charge_items_pkey");

                    b.HasIndex("ChargeTypeId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("TenantId");

                    b.ToTable("shipment_charge_items", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.ShipmentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Article")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("article");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<decimal>("Rate")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rate");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_amount");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasDefaultValue(0m)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("shipment_items_pkey");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("TenantId");

                    b.ToTable("shipment_items", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.ShipmentStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_user_id");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer")
                        .HasColumnName("from_status");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("location");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remarks");

                    b.Property<long>("ShipmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("shipment_id");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("shipment_status_history_pkey");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("TenantId");

                    b.ToTable("shipment_status_history", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("tenants_pkey");

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "DEFAULT",
                            CreatedAt = new DateTime(2026, 4, 3, 15, 56, 50, 696, DateTimeKind.Unspecified).AddTicks(5250),
                            IsActive = true,
                            Name = "Default Organization"
                        });
                });

            modelBuilder.Entity("KTransport.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Mobile")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mobile");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 3, 15, 56, 50, 696, DateTimeKind.Unspecified).AddTicks(5250),
                            FullName = "Kundan Kumar",
                            IsActive = true,
                            Mobile = "9504600060",
                            Password = "$2a$11$0aBw4j5tM1Ew2k5hF8O/TehI5jY9K2HkZ0K6o0tM6dYp/1R9Gq8m6",
                            Role = "admin",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("KTransport.API.Models.WithoutGstBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingClerk")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("booking_clerk");

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("text")
                        .HasColumnName("consignee_address");

                    b.Property<string>("ConsigneeMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consignee_mobile");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consignee_name");

                    b.Property<string>("ConsignerMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consigner_mobile");

                    b.Property<string>("ConsignerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consigner_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("DeliveryStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_location");

                    b.Property<decimal?>("GoodsValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("goods_value");

                    b.Property<DateOnly?>("GrDate")
                        .HasColumnType("date")
                        .HasColumnName("gr_date");

                    b.Property<string>("GrNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gr_no");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Paid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("paid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<decimal?>("Tbb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tbb");

                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("11111111-1111-1111-1111-111111111111"))
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_location");

                    b.Property<decimal?>("ToPay")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("to_pay");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TruckNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("truck_no");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("without_gst_bills_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TenantId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "GrNo" }, "without_gst_bills_gr_no_key")
                        .IsUnique();

                    b.ToTable("without_gst_bills", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Challan", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "CreatedByNavigation")
                        .WithMany("ChallanCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("KTransport.API.Models.User", "ModifiedByNavigation")
                        .WithMany("ChallanModifiedByNavigations")
                        .HasForeignKey("ModifiedBy");

                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany("Challans")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_challan_tenant");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KTransport.API.Models.ChallanDetail", b =>
                {
                    b.HasOne("KTransport.API.Models.BillType", "BillType")
                        .WithMany("ChallanDetails")
                        .HasForeignKey("BillTypeId")
                        .HasConstraintName("FK_ChallanDetail_BillType");

                    b.HasOne("KTransport.API.Models.Challan", "Challan")
                        .WithMany("ChallanDetails")
                        .HasForeignKey("ChallanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChallanDetail_Challan");

                    b.Navigation("BillType");

                    b.Navigation("Challan");
                });

            modelBuilder.Entity("KTransport.API.Models.Charge", b =>
                {
                    b.HasOne("KTransport.API.Models.GstBill", "Bill")
                        .WithOne("Charge")
                        .HasForeignKey("KTransport.API.Models.Charge", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charges_bill");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("KTransport.API.Models.ChargeType", b =>
                {
                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charge_types_tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KTransport.API.Models.GoodsDetail", b =>
                {
                    b.HasOne("KTransport.API.Models.GstBill", "Bill")
                        .WithMany("GoodsDetails")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goods_bill");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("KTransport.API.Models.GstBill", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "CreatedByNavigation")
                        .WithMany("GstBillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_created_by");

                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany("GstBills")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gst_bills_tenant");

                    b.HasOne("KTransport.API.Models.User", "UpdatedByNavigation")
                        .WithMany("GstBillUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_updated_by");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("KTransport.API.Models.NumberingSequence", b =>
                {
                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KTransport.API.Models.Shipment", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_shipments_created_by");

                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipments_tenant");

                    b.HasOne("KTransport.API.Models.User", "UpdatedByNavigation")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_shipments_updated_by");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("KTransport.API.Models.ShipmentChargeItem", b =>
                {
                    b.HasOne("KTransport.API.Models.ChargeType", "ChargeType")
                        .WithMany("ShipmentChargeItems")
                        .HasForeignKey("ChargeTypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipment_charge_items_type");

                    b.HasOne("KTransport.API.Models.Shipment", "Shipment")
                        .WithMany("ChargeItems")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_charge_items_shipment");

                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargeType");

                    b.Navigation("Shipment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KTransport.API.Models.ShipmentItem", b =>
                {
                    b.HasOne("KTransport.API.Models.Shipment", "Shipment")
                        .WithMany("Items")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_items_shipment");

                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KTransport.API.Models.ShipmentStatusHistory", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_shipment_history_user");

                    b.HasOne("KTransport.API.Models.Shipment", "Shipment")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shipment_history_shipment");

                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Shipment");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KTransport.API.Models.User", b =>
                {
                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_tenant");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KTransport.API.Models.WithoutGstBill", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "CreatedByNavigation")
                        .WithMany("WithoutGstBillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_wgst_created_by");

                    b.HasOne("KTransport.API.Models.Tenant", "Tenant")
                        .WithMany("WithoutGstBills")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wgst_tenant");

                    b.HasOne("KTransport.API.Models.User", "UpdatedByNavigation")
                        .WithMany("WithoutGstBillUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_wgst_updated_by");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Tenant");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("KTransport.API.Models.BillType", b =>
                {
                    b.Navigation("ChallanDetails");
                });

            modelBuilder.Entity("KTransport.API.Models.Challan", b =>
                {
                    b.Navigation("ChallanDetails");
                });

            modelBuilder.Entity("KTransport.API.Models.ChargeType", b =>
                {
                    b.Navigation("ShipmentChargeItems");
                });

            modelBuilder.Entity("KTransport.API.Models.GstBill", b =>
                {
                    b.Navigation("Charge");

                    b.Navigation("GoodsDetails");
                });

            modelBuilder.Entity("KTransport.API.Models.Shipment", b =>
                {
                    b.Navigation("ChargeItems");

                    b.Navigation("Items");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("KTransport.API.Models.Tenant", b =>
                {
                    b.Navigation("Challans");

                    b.Navigation("GstBills");

                    b.Navigation("Users");

                    b.Navigation("WithoutGstBills");
                });

            modelBuilder.Entity("KTransport.API.Models.User", b =>
                {
                    b.Navigation("ChallanCreatedByNavigations");

                    b.Navigation("ChallanModifiedByNavigations");

                    b.Navigation("GstBillCreatedByNavigations");

                    b.Navigation("GstBillUpdatedByNavigations");

                    b.Navigation("WithoutGstBillCreatedByNavigations");

                    b.Navigation("WithoutGstBillUpdatedByNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
