// <auto-generated />
using System;
using KTransport.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KTransport.API.Migrations
{
    [DbContext(typeof(KTransportDbContext))]
    [Migration("20260822172624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KTransport.API.Models.BillType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id")
                        .HasName("BillType_pkey");

                    b.ToTable("BillType", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Challan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("ChallanDate")
                        .HasColumnType("date")
                        .HasColumnName("ChallanDate");

                    b.Property<string>("ChallanNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ChallanNo");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DriverName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("DriverName");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("FromLocation");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LorryNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("LorryNo");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("Remarks");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ToLocation");

                    b.Property<string>("VoiceDriverName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("VoiceDriverName");

                    b.HasKey("Id")
                        .HasName("challan_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ModifiedBy");

                    b.ToTable("challan", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.ChallanDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BillNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("BillNo");

                    b.Property<int?>("BillTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("BillTypeId");

                    b.Property<long>("ChallanId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChallanId");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ConsigneeName");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedDate")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Destination")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("Destination");

                    b.Property<decimal?>("FreightAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("FreightAmount");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Remarks");

                    b.HasKey("Id")
                        .HasName("challanDetail_pkey");

                    b.HasIndex("BillTypeId");

                    b.HasIndex("ChallanId");

                    b.ToTable("challandetail", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("DdCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("dd_charge")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("Freight")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("freight")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("GrandTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("grand_total");

                    b.Property<decimal?>("Hamali")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("hamali")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("OtherCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("other_charge")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("ServiceCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("service_charge")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("StCharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("st_charge")
                        .HasDefaultValueSql("0");

                    b.HasKey("Id")
                        .HasName("charges_pkey");

                    b.HasIndex(new[] { "BillId" }, "charges_bill_id_key")
                        .IsUnique();

                    b.ToTable("charges", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.GoodsDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Article")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("article");

                    b.Property<int>("BillId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("rate");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("goods_details_pkey");

                    b.HasIndex("BillId");

                    b.ToTable("goods_details", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.GstBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingClerk")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("booking_clerk");

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("text")
                        .HasColumnName("consignee_address");

                    b.Property<string>("ConsigneeGstNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("consignee_gst_no");

                    b.Property<string>("ConsigneeMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consignee_mobile");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consignee_name");

                    b.Property<string>("Consigneeraddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consigneeraddress");

                    b.Property<string>("ConsignerGstNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("consigner_gst_no");

                    b.Property<string>("ConsignerMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consigner_mobile");

                    b.Property<string>("ConsignerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consigner_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("DeliveryStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_location");

                    b.Property<decimal?>("GoodsValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("goods_value");

                    b.Property<DateOnly?>("GrDate")
                        .HasColumnType("date")
                        .HasColumnName("gr_date");

                    b.Property<string>("GrNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gr_no");

                    b.Property<string>("GstPaidBy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gst_paid_by");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Paid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("paid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<decimal?>("Tbb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tbb");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_location");

                    b.Property<decimal?>("ToPay")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("to_pay");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TruckNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("truck_no");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("gst_bills_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "GrNo" }, "gst_bills_gr_no_key")
                        .IsUnique();

                    b.ToTable("gst_bills", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Mobile")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("mobile");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.WithoutGstBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingClerk")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("booking_clerk");

                    b.Property<string>("ConsigneeAddress")
                        .HasColumnType("text")
                        .HasColumnName("consignee_address");

                    b.Property<string>("ConsigneeMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consignee_mobile");

                    b.Property<string>("ConsigneeName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consignee_name");

                    b.Property<string>("ConsignerMobile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("consigner_mobile");

                    b.Property<string>("ConsignerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consigner_name");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("DeliveryStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("delivery_status");

                    b.Property<string>("FromLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("from_location");

                    b.Property<decimal?>("GoodsValue")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("goods_value");

                    b.Property<DateOnly?>("GrDate")
                        .HasColumnType("date")
                        .HasColumnName("gr_date");

                    b.Property<string>("GrNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gr_no");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_no");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal?>("Paid")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("paid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<decimal?>("Tbb")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tbb");

                    b.Property<string>("ToLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("to_location");

                    b.Property<decimal?>("ToPay")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("to_pay");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("TruckNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("truck_no");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("without_gst_bills_pkey");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex(new[] { "GrNo" }, "without_gst_bills_gr_no_key")
                        .IsUnique();

                    b.ToTable("without_gst_bills", (string)null);
                });

            modelBuilder.Entity("KTransport.API.Models.Challan", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "CreatedByNavigation")
                        .WithMany("ChallanCreatedByNavigations")
                        .HasForeignKey("CreatedBy");

                    b.HasOne("KTransport.API.Models.User", "ModifiedByNavigation")
                        .WithMany("ChallanModifiedByNavigations")
                        .HasForeignKey("ModifiedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("ModifiedByNavigation");
                });

            modelBuilder.Entity("KTransport.API.Models.ChallanDetail", b =>
                {
                    b.HasOne("KTransport.API.Models.BillType", "BillType")
                        .WithMany("ChallanDetails")
                        .HasForeignKey("BillTypeId")
                        .HasConstraintName("FK_ChallanDetail_BillType");

                    b.HasOne("KTransport.API.Models.Challan", "Challan")
                        .WithMany("ChallanDetails")
                        .HasForeignKey("ChallanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChallanDetail_Challan");

                    b.Navigation("BillType");

                    b.Navigation("Challan");
                });

            modelBuilder.Entity("KTransport.API.Models.Charge", b =>
                {
                    b.HasOne("KTransport.API.Models.GstBill", "Bill")
                        .WithOne("Charge")
                        .HasForeignKey("KTransport.API.Models.Charge", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_charges_bill");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("KTransport.API.Models.GoodsDetail", b =>
                {
                    b.HasOne("KTransport.API.Models.GstBill", "Bill")
                        .WithMany("GoodsDetails")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_goods_bill");

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("KTransport.API.Models.GstBill", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "CreatedByNavigation")
                        .WithMany("GstBillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_created_by");

                    b.HasOne("KTransport.API.Models.User", "UpdatedByNavigation")
                        .WithMany("GstBillUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_updated_by");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("KTransport.API.Models.WithoutGstBill", b =>
                {
                    b.HasOne("KTransport.API.Models.User", "CreatedByNavigation")
                        .WithMany("WithoutGstBillCreatedByNavigations")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_wgst_created_by");

                    b.HasOne("KTransport.API.Models.User", "UpdatedByNavigation")
                        .WithMany("WithoutGstBillUpdatedByNavigations")
                        .HasForeignKey("UpdatedBy")
                        .HasConstraintName("fk_wgst_updated_by");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("KTransport.API.Models.BillType", b =>
                {
                    b.Navigation("ChallanDetails");
                });

            modelBuilder.Entity("KTransport.API.Models.Challan", b =>
                {
                    b.Navigation("ChallanDetails");
                });

            modelBuilder.Entity("KTransport.API.Models.GstBill", b =>
                {
                    b.Navigation("Charge");

                    b.Navigation("GoodsDetails");
                });

            modelBuilder.Entity("KTransport.API.Models.User", b =>
                {
                    b.Navigation("ChallanCreatedByNavigations");

                    b.Navigation("ChallanModifiedByNavigations");

                    b.Navigation("GstBillCreatedByNavigations");

                    b.Navigation("GstBillUpdatedByNavigations");

                    b.Navigation("WithoutGstBillCreatedByNavigations");

                    b.Navigation("WithoutGstBillUpdatedByNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
