-- ============================================================================
-- DOMAIN EVOLUTION SCRIPT: MULTI-TENANT MANIFESTS & MULTI-INVOICE REFERENCES
-- Compatible with PostgreSQL for KTransport SaaS TMS
-- ============================================================================

-- 1. Ensure columns exist on 'shipments' table
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS origin_hub_id bigint NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS destination_hub_id bigint NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS current_hub_id bigint NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS delivery_type character varying(50) NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS eway_bill_no character varying(50) NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS eway_bill_valid_upto timestamp without time zone NULL;

-- 2. Create 'consignment_invoice_references' table for Many-to-Many Customer Goods Invoices
CREATE TABLE IF NOT EXISTS consignment_invoice_references (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
    shipment_id bigint NOT NULL,
    customer_invoice_no character varying(50) NOT NULL,
    customer_invoice_date date NOT NULL DEFAULT CURRENT_DATE,
    declared_goods_value numeric(14,2) NOT NULL DEFAULT 0,
    eway_bill_no character varying(50) NULL,
    eway_bill_date date NULL,
    eway_bill_valid_upto timestamp without time zone NULL,
    document_type character varying(50) NULL DEFAULT 'TaxInvoice',
    package_count integer NULL,
    weight_kg numeric(12,3) NULL,
    commodity_description character varying(250) NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_by integer NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consignment_invoices_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_consignment_invoices_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS consignment_invoices_tenant_shipment_inv_idx 
    ON consignment_invoice_references (tenant_id, shipment_id, customer_invoice_no);

-- 3. Create 'manifests' table (Loading Sheets / Consolidated e-Way Bill Form EWB-02)
CREATE TABLE IF NOT EXISTS manifests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
    manifest_no character varying(50) NOT NULL,
    manifest_date date NOT NULL DEFAULT CURRENT_DATE,
    origin_hub_id bigint NULL,
    destination_hub_id bigint NULL,
    trip_id bigint NULL,
    consolidated_eway_bill_no character varying(50) NULL,
    consolidated_eway_bill_date timestamp without time zone NULL,
    seal_no character varying(100) NULL,
    loading_supervisor_name character varying(150) NULL,
    remarks character varying(500) NULL,
    status integer NOT NULL DEFAULT 0, -- 0: Draft, 1: Finalized, 2: Loaded, 3: Dispatched, 4: InTransit, 5: Arrived, 6: Unloaded, 7: Closed, 8: Cancelled
    total_consignments integer NOT NULL DEFAULT 0,
    total_packages integer NOT NULL DEFAULT 0,
    total_weight_kg numeric(12,3) NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    created_by integer NULL,
    updated_by integer NULL,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NULL,
    CONSTRAINT fk_manifests_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_manifests_origin_hub FOREIGN KEY (origin_hub_id) REFERENCES locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_manifests_dest_hub FOREIGN KEY (destination_hub_id) REFERENCES locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_manifests_trip FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS manifests_tenant_manifest_no_key 
    ON manifests (tenant_id, manifest_no);

-- 4. Create 'manifest_items' table
CREATE TABLE IF NOT EXISTS manifest_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000001',
    manifest_id bigint NOT NULL,
    shipment_id bigint NOT NULL,
    target_destination_hub_id bigint NULL,
    loaded_packages integer NOT NULL DEFAULT 0,
    loaded_weight_kg numeric(12,3) NOT NULL DEFAULT 0,
    unloading_status integer NOT NULL DEFAULT 0, -- 0: Loaded, 1: ReceivedIntact, 2: Shortage, 3: Excess, 4: Damaged
    received_packages integer NULL,
    shortage_packages integer NULL,
    damaged_packages integer NULL,
    unloaded_at_hub_id bigint NULL,
    unloaded_date timestamp without time zone NULL,
    discrepancy_remarks character varying(500) NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_manifest_items_tenant FOREIGN KEY (tenant_id) REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_manifest_items_manifest FOREIGN KEY (manifest_id) REFERENCES manifests (id) ON DELETE CASCADE,
    CONSTRAINT fk_manifest_items_shipment FOREIGN KEY (shipment_id) REFERENCES shipments (id) ON DELETE CASCADE,
    CONSTRAINT fk_manifest_items_target_hub FOREIGN KEY (target_destination_hub_id) REFERENCES locations (id) ON DELETE SET NULL,
    CONSTRAINT fk_manifest_items_unloaded_hub FOREIGN KEY (unloaded_at_hub_id) REFERENCES locations (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS manifest_items_tenant_manifest_shipment_idx 
    ON manifest_items (tenant_id, manifest_id, shipment_id);

-- 5. Data Backfill: Populate consignment_invoice_references from existing shipments
INSERT INTO consignment_invoice_references (
    tenant_id, 
    shipment_id, 
    customer_invoice_no, 
    customer_invoice_date, 
    declared_goods_value, 
    document_type, 
    is_active, 
    created_at
)
SELECT 
    s.tenant_id,
    s.id,
    s.invoice_no,
    COALESCE(s.invoice_date, s.shipment_date, CURRENT_DATE),
    COALESCE(s.goods_value, 0),
    'TaxInvoice',
    true,
    CURRENT_TIMESTAMP
FROM shipments s
WHERE s.invoice_no IS NOT NULL 
  AND TRIM(s.invoice_no) <> ''
  AND NOT EXISTS (
      SELECT 1 FROM consignment_invoice_references cir 
      WHERE cir.shipment_id = s.id AND cir.customer_invoice_no = s.invoice_no
  );
